name: CI

env:
    CI: true
    GOOGLE_TRANSLATION_API_KEY: ${{ secrets.GOOGLE_TRANSLATION_API_KEY }}
    MICROSOFT_TRANSLATION_API_KEY: ${{ secrets.MICROSOFT_TRANSLATION_API_KEY }}
    DEEPL_TRANSLATION_API_KEY: ${{ secrets.DEEPL_TRANSLATION_API_KEY }}

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install libraries
              run: sudo apt-get install -y diffutils exiftool

            - name: Install composer
              uses: php-actions/composer@v6
              with:
                  php_version: '8.1'
                  version: 2.x

            - name: PHPUnit tests
              uses: php-actions/phpunit@v3
              with:
                  php_extensions: gd
