name: CI

env:
    CI: true
    GOOGLE_TRANSLATION_API_KEY: ${{ secrets.GOOGLE_TRANSLATION_API_KEY }}
    MICROSOFT_TRANSLATION_API_KEY: ${{ secrets.MICROSOFT_TRANSLATION_API_KEY }}
    DEEPL_TRANSLATION_API_KEY: ${{ secrets.DEEPL_TRANSLATION_API_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
    GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}

on: [push]

jobs:
    build-test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: ['ubuntu-latest', 'macos-latest']
                php-versions: ['7.4', '8.0', '8.1']

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }})

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                       sudo apt-get install coreutils
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                       brew install coreutils
                  fi
              shell: bash

            - name: PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: gd
                  tools: composer, phpunit

            - name: Composer
              run: composer install --no-interaction

            - name: PHPUnit
              run: ./vendor/bin/phpunit
