name: CI

env:
    CI: true
    GOOGLE_TRANSLATION_API_KEY: ${{ secrets.GOOGLE_TRANSLATION_API_KEY }}
    MICROSOFT_TRANSLATION_API_KEY: ${{ secrets.MICROSOFT_TRANSLATION_API_KEY }}
    DEEPL_TRANSLATION_API_KEY: ${{ secrets.DEEPL_TRANSLATION_API_KEY }}

on: [push]

jobs:
    build-test:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
                php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }})

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install composer
              uses: php-actions/composer@v6
              with:
                  version: latest
                  php_version: ${{ matrix.php-versions }}

            - name: PHPUnit tests
              uses: php-actions/phpunit@v3
              with:
                  version: latest
                  php_version: ${{ matrix.php-versions }}
                  php_extensions: gd
